### PR TITLE
Rename README to README.rst

### PR DESCRIPTION
**Pull request by msabramo**
so GitHub can render it nicely.

Check out how much better https://github.com/msabramo/fancycompleter/tree/rename-readme looks.

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks!
I'd prefer to convert it to markdown though (and rename it to `README.md` for clarity then probably), which appears to be simpler in general.
What do you think?

**Comment by blueyed** [comment]
..but this is much simpler for now.. :)

**Comment by blueyed** [comment]
Thanks!

**Comment by msabramo** [comment]
Yeah, I prefer Markdown myself, but I didn't know if you were open to switching to Markdown.

**Pull request merged**
