### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by theY4Kman**
This is a simple Python .gitignore template

### CODE REVIEW

**Comment by blueyed** [comment]
Sorry, I do not like those all-in-one gitignore files - you should rather have most of this / what you need in your global gitignore file.

What is bothering you / not ignored in this repo?

**Comment by theY4Kman** [comment]
Oooh, interesting! Is it partly 'cause they catch waaaay too much? (I've been bitten by things like `lib/` being included.)

Adding a `.gitignore` was in response to these guys:
```
	.eggs/
	.tox/
	__pycache__/
	fancycompleter.egg-info/
	fancycompleter.pyc
	testing/__init__.pyc
	testing/__pycache__/
```

**Comment by blueyed** [comment]
Yeah, it should not be too generic.

I'd be fine by having one to exclude `*.pyc`, `.eggs`, `.tox`, and `*.egg-info` then - but still recommend having this in a global gitignore file (`~/.config/git/ignore`).

**Comment by blueyed** [comment]
Closing as per previous comments.

**Pull request closed without merging**
